// Appends one lesson to docs/learning-log.md.
//
// Self-contained on purpose: Node built-ins only, no package.json, no install.
// Copy this file into any repo that keeps a learning log and it works unchanged.
//
// Usage:
//   node scripts/log-lesson.mjs "the lesson, in one sentence"
//
// This script never runs from a hook and never blocks a commit. A gate that
// blocks on documentation makes deleting the entry the cheapest way to commit,
// which destroys the lessons it was meant to protect. Enforcement here is
// construction: the entry is built correctly or it is refused before it lands.
//
// Known boundary, stated rather than hidden: the multi-line guard below fires
// when the process is spawned with an argv array, which is how an agent tool
// invokes it — verified, exit 1 and nothing written. Git Bash on Windows
// truncates a quoted argument at an embedded newline BEFORE node starts, so the
// script receives a valid single-line lesson and has no signal to detect the
// loss. Nothing inside this file can close that; the script echoes back the
// exact entry it wrote so a truncation is at least visible in the output.
//
// The 300-character ceiling is measured, not guessed. Across the 82 entries in
// this repo's log the p25 is 278 characters and the median is 498: three
// quarters of the corpus had already drifted past the "one short sentence" rule
// the file itself declares. 300 keeps the most disciplined quarter of real
// history and refuses the essays. An investigation that will not fit belongs in
// an ADR or a postmortem, with a one-line lesson pointing at it from here.

import { execFileSync } from 'node:child_process';
import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const MAX_LENGTH = 300;
const LOG_PATH = 'docs/learning-log.md';

const HEADER = `# Learning Log (Vitácora)

A human-readable record of *why* things in this repo are the way they are:
decisions taken and non-obvious problems solved, so future sessions inherit the
reasoning instead of rediscovering it.

This is a memory aid, **not** a substitute for deterministic guards. Whenever a
lesson can be enforced (linter, test, \`go vet\`, pre-commit gate), do that too —
this file only explains the *why*, it never replaces the *how*.

## How to append

Run \`node scripts/log-lesson.mjs "the lesson"\`. It stamps the date, enforces the
one-line format, and appends. Do not edit this file by hand.

- One lesson per line, ${MAX_LENGTH} characters maximum.
- Format: \`- [YYYY-MM-DD]: text\`
- Newest entries at the bottom. Never rewrite past entries; add a new line if
  something changes.

## Entries
`;

function fail(message, hint) {
  console.error(`log-lesson: ${message}`);
  if (hint) console.error(`log-lesson: ${hint}`);
  process.exit(1);
}

// Exactly one argument, deliberately. Joining argv with spaces would silently
// repair a lesson the shell had already mangled: on Windows a newline inside a
// quoted argument splits it, and the join would paste the fragments back into a
// plausible-looking entry that has lost text. Requiring one argument turns every
// such split into a visible refusal instead of quiet data loss.
const args = process.argv.slice(2);

if (args.length === 0 || args[0].trim() === '') {
  fail('no lesson given.', 'usage: node scripts/log-lesson.mjs "the lesson, in one sentence"');
}

if (args.length > 1) {
  fail(
    `expected one quoted argument, got ${args.length}.`,
    'wrap the whole lesson in quotes. If it was already quoted, it contains a newline that your shell split on — write it as a single line.'
  );
}

const lesson = args[0].trim();

if (/[\r\n]/.test(lesson)) {
  fail(
    'the lesson spans multiple lines; one entry is one physical line.',
    'compress it to the lesson itself, or write the investigation as an ADR or postmortem and reference it in one line here.'
  );
}

if (lesson.length > MAX_LENGTH) {
  fail(
    `the lesson is ${lesson.length} characters, over the ${MAX_LENGTH} ceiling.`,
    'a lesson that will not fit has not been extracted yet — you are storing the investigation. Put that in an ADR or a postmortem and log the one-line lesson that points at it.'
  );
}

let root;
try {
  // eslint-disable-next-line sonarjs/no-os-command-from-path -- Resolving `git` from PATH is required for portability: this script is developer-invoked tooling that must work unchanged on Windows, macOS, and Linux, where git lives at a different absolute path on each. The rule guards against PATH hijacking, which here presupposes an attacker who already controls the developer's shell environment; nothing this script reads or writes is a new capability for them.
  root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
} catch {
  fail('not inside a git repository.');
}

const file = path.join(root, LOG_PATH);

if (!existsSync(file)) {
  writeFileSync(file, HEADER, 'utf8');
  console.log(`log-lesson: created ${LOG_PATH}`);
}

const date = new Date().toISOString().slice(0, 10);
const entry = `- [${date}]: ${lesson}`;

const current = readFileSync(file, 'utf8');
const separator = current.endsWith('\n') ? '' : '\n';

appendFileSync(file, `${separator}${entry}\n`, 'utf8');

console.log(`log-lesson: appended to ${LOG_PATH}`);
console.log(entry);
